version: "3.8"
volumes:
  db-store:
services:
  app:
    build: ./infra/docker/php
    volumes:
      - .:/var/www/html
    ports:
      - 8080:80
  db:
    build: ./infra/docker/mysql
    ports:
      - 3306:3306
    volumes:
      - db-store:/var/lib/mysql
